### ISSUE TITLE
In during install appear error

### ISSUE THREAD

**Issue by ambyte** [AllenDang/gform#1]
$ cd gform/src && gomake
make -C pkg/gform               clean
make[1]: Entering directory `/d/projects/GO/src/gform/src/pkg/gform'
rm -rf *.o *.a *.[568vq] [568vq].out *.so _obj _test _testmain.go *.exe _cgo* te
st.out build.out
make[1]: Leaving directory`/d/projects/GO/src/gform/src/pkg/gform'
make -C pkg/gform               install
make[1]: Entering directory `/d/projects/GO/src/gform/src/pkg/gform'
8g   -p gform -o _go_.8 init.go rect.go color.go font.go imagelist.go globalvars
.go util.go pen.go brush.go canvas.go icon.go msghandlerregistry.go controller.g
o eventhandler.go eventarg.go eventmanager.go controlbase.go wndproc.go w32contr
ol.go dialog.go form.go customcontrol.go buttons.go statics.go edit.go progressb
ar.go commondlgs.go listview.go tooltip.go app.go
brush.go:14: undefined: w32.BS_SOLID
canvas.go:61: undefined: user32.FillRect
make[1]: *** [_go_.8] Error 1
make[1]: Leaving directory`/d/projects/GO/src/gform/src/pkg/gform'
make: **\* [all] Error 2

w32 installed good

**Comment by AllenDang** [comment]
You need to update w32 to newest version.

2011/12/23 Sergey Gulyaev
reply@reply.github.com:
