### ISSUE TITLE
Demo canvas import 

### ISSUE THREAD

**Issue by locky37** [AllenDang/gform#7]
demo\canvas>go build testcanvas.go

testcanvas.go:4:2: import "gform": cannot find package
testcanvas.go:6:2: import "w32": cannot find package

File testcanvas.go

import (
    "gform"
    "syscall"
    "w32"
)

Change to

import (
    "syscall"
    "github.com/AllenDang/gform"
        "github.com/AllenDang/w32"
)

**Comment by AllenDang** [comment]
Thanks! I updated the code, please update to get the fix.

**Comment by locky37** [comment]
I apologize that not all of the data provided on the OS

Windows 7 SP1 amd64

Bug:

c:\Project\AllenDang-gform-1abee3a\demo\canvas>go build testcanvas.go

c:\Project\AllenDang-gform-1abee3a\demo\canvas>testcanvas.exe
panic: SizeofResource failed

goroutine 1 [running]:
github.com/AllenDang/w32.SizeofResource(0x400000, 0x0, 0xf84003e050, 0x0, 0x0, .
..)
        C:/Go/src/pkg/github.com/AllenDang/w32/kernel32.go:145 +0xd2
github.com/AllenDang/gform.NewBitmapFromResource(0x400000, 0x64, 0xf84003e050, 0
xf8000000ff, 0x0, ...)
        C:/Go/src/pkg/github.com/AllenDang/gform/bitmap.go:56 +0xf4
main.onpaint(0xf840037de0, 0x423d11)
        c:/Project/AllenDang-gform-1abee3a/demo/canvas/testcanvas.go:17 +0x12a
github.com/AllenDang/gform.(_EventManager).Fire(0xf8400470a0, 0xf840037de0, 0x46
9220, 0xf84003e040)
        C:/Go/src/pkg/github.com/AllenDang/gform/eventmanager.go:11 +0x38
github.com/AllenDang/gform.generalWndProc(0xf0844, 0xf, 0x0, 0x0, 0x0, ...)
        C:/Go/src/pkg/github.com/AllenDang/gform/wndproc.go:93 +0x4e6
----- stack segment boundary -----
syscall.Syscall(0x7756991c, 0x1, 0xf8400461e0, 0x0, 0x0, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist309699735/go/src/pkg/runti
me/zsyscall_windows_amd64.c:74 +0x55
syscall.(_Proc).Call(0xf840037da0, 0x361f18, 0x100000001, 0x0, 0x0, ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist309699735/go/src/pkg/sysca
ll/dll_windows.go:113 +0x1a8
syscall.(*LazyProc).Call(0xf840045480, 0x361f18, 0x100000001, 0x0, 0xf840037d40,
 ...)
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist309699735/go/src/pkg/sysca
ll/dll_windows.go:248 +0x6f
github.com/AllenDang/w32.DispatchMessage(0xf8400461e0, 0x0, 0x0, 0xfc00000001)
        C:/Go/src/pkg/github.com/AllenDang/w32/user32.go:227 +0x7a
github.com/AllenDang/gform.RunMainLoop(0xf840047000, 0xc80000012c)
        C:/Go/src/pkg/github.com/AllenDang/gform/app.go:59 +0x96
main.main()
        c:/Project/AllenDang-gform-1abee3a/demo/canvas/testcanvas.go:37 +0x97

goroutine 2 [syscall]:
created by runtime.main
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist309699735/go/src/pkg/runti
me/proc.c:221

**Comment by AllenDang** [comment]
Are you using 64bit windows? If so, gform currently cannot support 64bit OS. I'm working on it.
