### ISSUE TITLE
呃 我想很多人真的很需要gform，能继续下去这个项目吗？

### ISSUE THREAD

**Issue by cocotyty** [AllenDang/gform#8]
关注很久了 希望能继续下去

用起来真的很舒服、、

**Comment by milak** [comment]
i d'like to use your API and you did a great work but the result is poor. I am missing many componants : trees, lists, etc.
Good luck for your work

**Comment by chor** [comment]
some issues when i get this project(my os : xp)

$ go get github.com/AllenDang/gform

# github.com/AllenDang/gform

D:\Go\src\pkg\github.com\AllenDang\gform\app.go:16: cannot use 8 (type uint) as
type uint32 in assignment
D:\Go\src\pkg\github.com\AllenDang\gform\bitmap.go:22: cannot use dib.DsBmih.BiW
idth (type int32) as type int in field value
D:\Go\src\pkg\github.com\AllenDang\gform\bitmap.go:23: cannot use dib.DsBmih.BiH
eight (type int32) as type int in field value
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:65: cannot use rc.Left (type
int32) as type int in function argument
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:65: cannot use rc.Top (type i
nt32) as type int in function argument
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:65: cannot use rc.Right (type
 int32) as type int in function argument
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:65: cannot use rc.Bottom (typ
e int32) as type int in function argument
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:81: cannot use w32Rect.Left (
type int32) as type int in function argument
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:81: cannot use w32Rect.Top (t
ype int32) as type int in function argument
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:81: cannot use w32Rect.Right
(type int32) as type int in function argument
D:\Go\src\pkg\github.com\AllenDang\gform\canvas.go:81: too many errors

**Comment by AllenDang** [comment]
I'm sorry, gform does't support 64bit OS...

**Comment by HughLo** [comment]
@shaform In my computer which installs WinXP SP3 the user32.dll does not contain SetWindowLongPtrW API. Therefore, I modify the implementation of w32.SetWindowLongPtr as below:

``` GO
func SetWindowLongPtr(hwnd HWND, index int, value uintptr) uintptr {
    exeProc := procSetWindowLongPtr
    err := procSetWindowLongPtr.Find()
    if err != nil {
        exeProc = procSetWindowLong
    }

    ret , _ , _ := exeProc.Call( uintptr(hwnd) , uintptr(index) , value )
    return ret
}
```

And it works at least for me!
